workflow and pom.xml

diff --git a/.github/workflows/main_seniorcarejava.yml b/.github/workflows/main_seniorcarejava.yml
--- a/.github/workflows/main_seniorcarejava.yml
+++ b/.github/workflows/main_seniorcarejava.yml
@@ -14,7 +14,7 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Set up Java version
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v3
         with:
           java-version: '17'
 
@@ -23,11 +23,18 @@ jobs:
           cd crud-senior-care
           mvn clean install -Dfile.encoding=UTF-8
 
+      - name: Verify WAR file exists
+        run: |
+          if [ ! -f crud-senior-care/target/*.war ]; then
+            echo "WAR file not found!"
+            exit 1
+          fi
+
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v3
         with:
           name: java-app
-          path: 'crud-senior-care/target/*.war'
+          path: crud-senior-care/target/*.war
 
   deploy:
     runs-on: ubuntu-latest
@@ -36,7 +43,7 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
+      id-token: write # This is required for requesting the JWT
 
     steps:
       - name: Download artifact from build job
@@ -47,14 +54,4 @@ jobs:
       - name: Login to Azure
         uses: azure/login@v1
         with:
-          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
-          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
-          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
-
-      - name: Deploy to Azure Web App
-        id: deploy-to-webapp
-        uses: azure/webapps-deploy@v2
-        with:
-          app-name: 'seniorcarejava'
-          slot-name: 'Production'
-          package: '*.war'
+          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3EC5E8ACBC8A4559A45042B39325
